### ISSUE TITLE
Replace `link:` with user-defined networking in docker-compose.yml

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#103]
## Problem

Our `docker-compose.yml` currently uses a deprecated `link` definition to allow for inter-container communication.

## Description

Replace the `link` with a user-defined network configuration in our `docker-compose.yml`.

**Comment by alainseys** [comment]
see my PR #107 where i have created a new network.

**Comment by alainseys** [comment]
@brylie is there a adjustment needed ?

**Comment by brylie** [comment]
@alainseys the PR looks good. I just returned from holiday, so am just now catching up on GitHub and email. I'll run the PR ASAP.

**Comment by brylie** [comment]
@alainseys thanks! The PR looks great :sunglasses:
