### ISSUE TITLE
RFC: Replace hard-coded footer with generic, block-based widget area

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#106]
## Problem

The footer area currently contains hard-coded structure and information including:
- social media links
- contact information/address
- copyright notice

## Description

Rather than hard-coding that information, consider allowing content editors to use generic WordPress blocks to structure the page footer. This could open up possibilities to not only changing the content but also the layout of the footer without requiring a designer or developer.

## Goals
- make the theme more site-agnostic (generic)
- enable content managers to make structured changes to site layout

## Additional context

Not only does WordPress 5.8 support block-based widget layout, it also helps users to create higher-level widget combinations, such as a "social media links" icon row.
![image](https://user-images.githubusercontent.com/17307/126800002-4321aca2-c50d-4fff-83da-5ebccce75801.png)

**Comment by annatuma** [comment]
I appreciate the desire to implement the footer in such a way as to be more flexible for editors, but I'd like us to think about if there's a way to ensure that the basics remain the same. A major goal with both the global (expandable) header and global footer was to ensure brand/information/experience consistency across all CC web properties. This is something that doesn't currently exist and confuses users when they end up on one site (e.g. Certs or Network) and see no tie to other CC sites.

This might be a case for templates, which are open to editors making changes to them, but the starting point is the same? Allowing for this flexibility also means we'll need documentation on what are "must haves" in a footer, such as our various policy links.

**Comment by brylie** [comment]
That makes sense. Perhaps some generic widgets can be used in a footer widget area while preserving the consistent layout for primary elements like social media icons and contact info.
