### ISSUE TITLE
Change default layout to allow Gutenberg full-width (no sidebar)

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#135]
## Problem

We are enabling Gutenberg to control page layout as part of #130 

## Description

Consider making the Gutenberg full-width template the default. The current default layout contains a sidebar, which may be deprecated in #132

- rename the `page.php` to `template-sidebar.php`
    - consider adding grid classes again to control the layout
- rename `template-no-sidebar.php` to `page.php`

## Additional context

Most of the Figma mockups don't contain a sidebar menu so the menu should not be the default template.

**Comment by alainseys** [comment]
> * grid classes

hy @brylie is there a how to described how we can test this out? i have the changes ready on my local dev enviroment not sure how to test this out

**Comment by brylie** [comment]
The developer docs can probably use some improvement. Basically,

1. run the development stack with `docker-compose up`
2. enable the creativecommons-base theme (using admin user created during installation)
3. create/publish a new page
4. view the page via the "view page" link
5. inspect the markup with dev tools (F12) to make sure the correct template rendered (no sidebar)

**Comment by alainseys** [comment]
> The developer docs can probably use some improvement. Basically,
> 
> 1. run the development stack with `docker-compose up`
> 2. enable the creativecommons-base theme (using admin user created during installation)
> 3. create/publish a new page
> 4. view the page via the "view page" link
> 5. inspect the markup with dev tools (F12) to make sure the correct template rendered (no sidebar)

OK I will test the code with these instructions

**Comment by alainseys** [comment]
> The developer docs can probably use some improvement. Basically,
> 
> 1. run the development stack with `docker-compose up`
> 2. enable the creativecommons-base theme (using admin user created during installation)
> 3. create/publish a new page
> 4. view the page via the "view page" link
> 5. inspect the markup with dev tools (F12) to make sure the correct template rendered (no sidebar)

just reviewed the PR #136 and no sidebar is applied
