### ISSUE TITLE
Add Slack button to README

### ISSUE THREAD

**Issue by alainseys** [creativecommons/creativecommons-base#137]
## Description
would it not be intresting to add a slack channel to github so we can chat while working on issues ? 

Add a Slack button to the project README that links to our Slack sign up page:

https://slack-signup.creativecommons.org/

![slack sign up button](https://camo.githubusercontent.com/fd2c87932477b197ddaebe65b96c27e5cb2b7361bdbf3036352df344369f041e/68747470733a2f2f636c6475702e636f6d2f496169506e44454141362e676966)

That way other contributors can join the conversation.

**Comment by brylie** [comment]
Feel free to join our Slack community: https://slack-signup.creativecommons.org/

I'm available on Slack throughout the day, and will gladly chat about all things open-source :-)

**Comment by brylie** [comment]
@alainseys I've changed this to be a task to add a Slack button to the README so other developers can join the discussion. Would you like to add the Slack button?

**Comment by alainseys** [comment]
> @alainseys I've changed this to be a task to add a Slack button to the README so other developers can join the discussion. Would you like to add the Slack button?

this is performed hopefully you like the button and the text i have added
