### ISSUE TITLE
Navigation menu text is white on white background

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#182]
## Description
The navigation menu is not visible due to the text being white on a white background:

![Peek 2022-02-08 15-44](https://user-images.githubusercontent.com/17307/152999662-44af5554-1688-49e2-b41f-b9d84c812d78.gif)

## Reproduction

1. start the development server
2. import the staging content
3. add the CC menu to the `main navigation` menu location
4. view the front page and notice the menu text is not visible

## Expectation

Menu text should be visible and have a high degree of contrast. The menu text should use the default font color, which is a shade of grey.

**Comment by MuluhGodson** [comment]
Hello @brylie 
I'll love to open a PR for this.
