### ISSUE TITLE
Breadcrumb text appears twice

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#183]
## Description
The breadcrumb is being rendered twice:

![image](https://user-images.githubusercontent.com/17307/153000637-945fc104-a189-4b9d-9341-66163562570e.png)

## Reproduction
1. start the development server
2. import the staging content
3. set any page as the front page
4. view the front page and notice the breadcrumb is rendered twice

## Expectation

The breadcrumb should only render once. The breadcrumb should be aligned with the overall theme container, rather than right against the edge of the screen.

**Comment by MuluhGodson** [comment]
I think by default, Yoast SEO renders breadcrumbs on pages. 
However, we also have some code to display the breadcrumbs. You can find it here: [creativecommons_base/header.php - Line 50](https://github.com/creativecommons/creativecommons-base/blob/main/header.php#L50). 

Removing this code will ensure that the breadcrumb only renders once per page.

**Comment by MuluhGodson** [comment]
Can I be assigned here?

**Comment by brylie** [comment]
Ok, ideally, it would only be defined in one place and included in all relevant locations, if possible.

**Comment by MuluhGodson** [comment]
> Ok, ideally, it would only be defined in one place and included in all relevant locations, if possible.

Yes exactly.
