### ISSUE TITLE
 Update style and fonts CDN to latest versions

### ISSUE THREAD

**Issue by MuluhGodson** [creativecommons/creativecommons-base#190]
## Problem
`creativecommons-base` still uses the old vocabulary imports. We have since separated the vocabulary project into three distinct projects and have published these 3 packages individually. 
## Description
Update the CDN imports to use the respective latest versions.

## Alternatives
Do nothing

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by MuluhGodson** [comment]
@brylie Can you assign me here?

**Comment by brylie** [comment]
@MuluhGodson, assigned :-)
