### ISSUE TITLE
[Feature] Consider removing Bulma CDN

### ISSUE THREAD

**Issue by MuluhGodson** [creativecommons/creativecommons-base#193]
## Problem
We already compile most (if not all) of Bulma into `vocabulary-styles`. Adding Bulma CDN to projects with `vocabulary-styles` makes the CSS redundant and a tard annoying to work through problems involving the CSS.
cc @brylie

**Comment by brylie** [comment]
This seems like a good idea. How much work would it entail to remove the Bulma CDN import? Is this just a matter of removing the CDN link, or would we need to include other aspects of Bulma in the Vocabulary Styles package?

**Comment by MuluhGodson** [comment]
> This seems like a good idea. How much work would it entail to remove the Bulma CDN import? Is this just a matter of removing the CDN link, or would we need to include other aspects of Bulma in the Vocabulary Styles package?

The only thing we need to do is remove the CDN link.

**Comment by brylie** [comment]
OK, let's go ahead and include that in the MVP or Staging milestone, as needed.

**Comment by MuluhGodson** [comment]
@brylie I am unable to self-assing. But I have opened a PR.
