### ISSUE TITLE
Add a linter and code formatter to the docs

### ISSUE THREAD

**Issue by JackieBinya** [creativecommons/creativecommons-base#26]
## Problem

Currently, in the docs directory, we do not have a coding standard enforced, so it is difficult to maintain code consistency.

## Description

I want to add the two npm modules [eslint](https://eslint.org/) and [prettier](https://prettier.io/) to the project as well as a script to automate linting and code formatting.

## Alternatives

 - N/A

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Cronus1007** [comment]
@JackieBinya  Here we can introduce `husky` pre-commit to automate the repo's formatting and this will make commits and review easy. But the problem that may arise that husky is `npm` module so first we have to initialise this repo with `npm init` since as per my observation code doesn't have a `package.json`

**Comment by JackieBinya** [comment]
@Cronus1007 please review this link/page and let me know if this is what you are looking for https://github.com/creativecommons/creativecommons-base/blob/docs/docs/package.json

Sorry for a late response its been hectic on my side.

**Comment by Cronus1007** [comment]
@JackieBinya  No worries. Yes I am referring https://github.com/creativecommons/creativecommons-base/blob/docs/docs/package.json this only. Also in this issue are you referring bash scripts to automate the process. 
So first of all let me write the prettier config files and then build few bash scripts to automate the process of formatting.

**Comment by Cronus1007** [comment]
Will soon send a PR fixing this issue. Also you can have a look at the PR https://github.com/creativecommons/creativecommons.github.io-source/pull/584
since I am implementing same in this issue as well .
https://github.com/creativecommons/creativecommons.github.io-source/issues/509

**Comment by Cronus1007** [comment]
@hugosolar  Lets close this commit then.

**Comment by zackkrida** [comment]
Fixed via #60
