### ISSUE TITLE
Resolve vue-eslint bug in Sidebar component in the docs directory

### ISSUE THREAD

**Issue by JackieBinya** [creativecommons/creativecommons-base#29]
## Description

The vue-eslint rule that restricts mixing _vue-for_ and _vue-if_ was broken in the sidebar component.

## Reproduction

1. Check out the docs branch by running the command _git checkout docs_ on your terminal
2. cd to _wp-content/themes/wp-theme-base/docs/src/components/Sidebar.vue_
3. Delete the statement _eslint disable rule_ on line 19
4. On the terminal run the script **npm run lint**
4. See error.

## Expectation

- An error is logged on the console, that outlines the vue-eslint rule that has been broken.

## Screenshots

The screenshot below captures the error
![linting-bug-sidebar](https://user-images.githubusercontent.com/50267279/93351976-a1871e80-f83a-11ea-890b-fa8f7e9c7a80.png)

## Environment

 - Device: Dell Laptop
 - OS: Ubuntu 20.04
 - Browser: N/A
 - Version: N/A
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by Cronus1007** [comment]
@JackieBinya  Let me take over this issue and resolve it

**Comment by JackieBinya** [comment]
@Cronus1007 sure may work on the issue. Let me know if you need any help.

**Comment by Cronus1007** [comment]
@JackieBinya  I have already removed  this line of code while working upon #60 PR  so it is now safe to close this issue as well and we can also close #26 issue

**Comment by zackkrida** [comment]
Fixed via #60
