### ISSUE TITLE
Figure out where source code is for Theme Base documentation

### ISSUE THREAD

**Issue by annatuma** [creativecommons/creativecommons-base#64]
We want to find the source code for this documentation: https://cc-wp-theme-base.netlify.app/getting-started

We want to ensure the source code is within a CC repository, so that it can be evolved as a developer and/or user guide over time.

## Proposal

Merge the `docs` branch into `main` to make it easier to find the documentation.

**Comment by brylie** [comment]
@JackieBinya, do you recall where you kept the source code for the CC WP Theme Base documentation? Is it in one of the CC repositories?

**Comment by brylie** [comment]
I found the [blog post by @JackieBinya](https://jackiebinya.github.io/posts/gsod-2020/gsod-report/) where they mention the [documentation source is in a `docs` branch of this repo](https://github.com/creativecommons/creativecommons-base/tree/docs/docs).

**Comment by JackieBinya** [comment]
Great @brylie. I only saw your message rn. Please let me know if there is anyway I can help.

**Comment by brylie** [comment]
I propose that we merge the `docs` branch into `main` to make it easier to find the documentation :smiley:

**Comment by JackieBinya** [comment]
@brylie they were supposed to be merged to main. But we held it off for some odd reason. But I guess now is as good a time as any. So yeah sure.
