### ISSUE TITLE
Consider deprecating Queulat

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#69]
## Problem

Remove the project dependency on [Queulat](https://github.com/felipelavinz/queulat).

## Description

The project depends on a WordPress development framework called Queulat. The Queulat framework has some possible shortcomings

- very limited documentation
- limited community contribution
- defining its own conventions
- has broken/abandoned dependencies
    - https://packagist.org/packages/anahkiasen/underscore-php

## Additional context

Before making the decision whether to deprecate Queulat, it is good to

- determine how Queulat is being used in the project
- identify alternatives in the WordPress development ecosystem
    - these should be ideally part of WordPress core and not some third-party, proprietary plugin 

## How is Queulat used?

Queulat is used to
- define the theme settings page
- create custom WordPress metaboxes

## What would be used instead of Queulat?

Use standard WordPress functions to define the theme options forms
- https://blog.templatetoaster.com/wordpress-settings-api-creating-theme-options/

Use conventional WordPress code to define metaboxes.
- https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/

## Related code
Queulat is used in the following files:

https://github.com/creativecommons/creativecommons-base/blob/39e72523afed695b4934f5cb131b14182e684345/inc/settings.php#L2-L11

https://github.com/creativecommons/creativecommons-base/blob/39e72523afed695b4934f5cb131b14182e684345/inc/metaboxes.php#L2-L5

https://github.com/creativecommons/creativecommons-base/blob/39e72523afed695b4934f5cb131b14182e684345/composer.json#L12-L17

## What to avoid?

Avoid adding new plugins to this theme, particular those with premium extensions or features.

**Comment by brylie** [comment]
@hugosolar could you share some of your thoughts on the Queulat framework?

**Comment by hugosolar** [comment]
Hello @brylie 
I agree about what you're saying. Queulat lacks of documentation, although in my opinion is a good tool for managing forms and metaboxes it saves a lot of time when you're building admin screens.
I think using WordPress itself will increase the development times but it's up to you.

I'd recommend this plugin instead

- [Fieldmanager](https://github.com/alleyinteractive/wordpress-fieldmanager)

it has much more documentation, last release is from 2020 and it's approved by WP VIP platform.

**Comment by brylie** [comment]
It's just strange to me that basic form building isn't part of WordPress core. Forms seem like a major component. The lack of simple form building has led to a fragmented ecosystem of projects trying to provide that functionality.

**Comment by hugosolar** [comment]
I'd tend to agree with your opinion, I feel like WordPress lacks so many things. Although, some of the functionality made by Queulat in this theme can be moved to something more related to the WordPress core for instance Gutenberg blocks (which made the editor work so much easy) or maybe something like shortcodes (thinking in the classic editor which will be supported for another year I think)

**Comment by brylie** [comment]
I moved this to the active sprint, since I am currently researching to what extent Queulat is being used by themes.
