### ISSUE TITLE
Install Composer within development container

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#73]
## Problem

Developers currently need to have Composer installed globally on their computers in order to develop this theme.

## Description

Installing Composer within the development container would mean fewer development dependencies. Further, the containerized Composer could install the composer dependencies automatically at build time.

Determine how to install Composer within the development container and then run the `composer install` command during the image build.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by alainseys** [comment]
You can place your development envrioment in a docker image there you can give the command to install composer and any other requirements. The only drawback to this is when you need to run a composer command you need to connect in to the container and perform the command there.

**Comment by brylie** [comment]
@alainseys do you know of a simple `Dockerfile` example that extends `wordpress:latest` and installs Composer in the development environment? 

The only examples I have found include convoluted steps, use a different base image/WP project structure, or have an entry point script that is barely intelligible. I'm trying to keep the development process as clear and simple as is possible.

**Comment by alainseys** [comment]
Hy @brylie a wordpress:latest i need to check what i alway do i make seperate containers and if its required they can talk to eachother.

eg:
- nginx
- mysql
- wordpress
- phpmyadmin
- composer

phpmyadmin -> mysql
composer -> wordpress 

i will dig in the image of wordpress, alternative you can send a command when the containers boots up to download composer and install it globaly.

**Comment by brylie** [comment]
Thanks, @alainseys! 

For what it's worth, the `docker-compose.yml` already has the basic pieces needed such as phpMyAdmin and `wp-cli`, while the 'wordpress:latest` handles web server configuration. So, I hope to keep the configuration to a minimum by only installing the missing Composer dependency, if possible.

**Comment by alainseys** [comment]
@brylie 

try by adding the following code to your docker-compose file (i added the paths from your docker-compose.yml file, just check them if they are correct)

bring the container up with the rebuild command this should add [composer](https://hub.docker.com/_/composer?tab=tags)
```
 composer:
    image: composer/composer
    container_name: myapp-composer
    working_dir: ./wp-app:/var/www/html
    restart: 'no'
    volumes:
      -  ../:/var/www/html/wp-content/themes/creativecommons-base
```

**Comment by brylie** [comment]
@alainseys, I get an error:

> ERROR: for composer  Cannot create container for service composer: the working directory './wp-app:/var/www/html' is invalid, it needs to be an absolute path

**Comment by brylie** [comment]
It would seem counter-intuitive that I would need to hard-code an absolute path in a multi-user development file.

**Comment by brylie** [comment]
It runs correctly when I change to `working_dir: /var/www/html`

**Comment by brylie** [comment]
I also need to add the `command: sh -c "composer install"` to the docker-compose composer service definition.

**Comment by alainseys** [comment]
> I also need to add the `command: sh -c "composer install"` to the docker-compose composer service definition.

you can supress this in a seperate docker file in your build process there you can give the run command (``RUN sh -c "composer install ``)

**Comment by brylie** [comment]
OK, thanks. For now, the `docker-compose.yml` is sufficient for all of the dependencies without the need to define any Dockerfile. See PR: #75
