### ISSUE TITLE
Use MariaDB in development container

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#74]
## Problem

The development container currently uses MySQL. However, our production systems tend to use MariaDB.

## Description

Change the `db` layer in the `docker-compose.yml` to use MariaDB image. Make sure the WordPress layer can still connect to the database.

**Comment by alainseys** [comment]
What version of mariadb are you using?

**Comment by alainseys** [comment]
see PR #80

**Comment by brylie** [comment]
@alainseys thank you so much! You rock :smiley:

**Comment by brylie** [comment]
Closed bby #80
