### ISSUE TITLE
Incompatible packages in composer.json

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#76]
Split from PR #75 

Related issue: #69 (due to abandoned dependency causing error below)

I am unable to install the package dependencies in composer.json due to incompatibilities.

```
Your lock file does not contain a compatible set of packages. Please run composer update.
| 
|   Problem 1
|     - doctrine/inflector is locked to version v1.2.0 and an update of this package was not requested.
|     - doctrine/inflector v1.2.0 requires php ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
|   Problem 2
|     - doctrine/inflector v1.2.0 requires php ^7.0 -> your php version (8.0.7) does not satisfy that requirement.
|     - felipelavinz/queulat v2019.4.2 requires doctrine/inflector v1.2.* -> satisfiable by doctrine/inflector[v1.2.0].
|     - felipelavinz/queulat is locked to version v2019.4.2 and an update of this package was not requested.
```

## Reproduction

1. run `composer install`
2. see error

## Expectation

Project dependencies would install correctly without conflict.

## Environment

 - Device: laptop
 - OS: Ubuntu 20.04

## Notes

- The [official Composer image](https://hub.docker.com/_/composer) does not support PHP below version 8.
- [Doctrine/inflector](https://github.com/doctrine/inflector) latest version is at 1.44.

**Comment by alainseys** [comment]
hy @brylie  you can try using a other wordpress tag with a newer version of php [here](https://github.com/docker-library/wordpress/blob/cdb836237e3af7bfd011957316f159c1e81bf29c/latest/php7.3/apache/Dockerfile) is a sugestion

**Comment by brylie** [comment]
@alainseys What are your thoughts on the error messages?

From what I can understand, it seems like the Composer image is using an internal version of PHP 8 when invoking the `composer install` command. Then, the installation fails since the `doctrine/inflector` package is not marked as compatible with PHP 8. I added a note in the issue description about the official Composer image using PHP 8.

The Queulat package, which is under consideration for removal #69, may be the root of this issue.

**Comment by alainseys** [comment]
doctorine have some issues if the version of php is been switched see [here](https://github.com/doctrine/inflector/issues/52) for some ref
