### ISSUE TITLE
Upgrade and clean up Composer dependencies

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#84]
## Problem

Not only do we have some dependency conflicts (#76), we also have some warnings about abandoned dependencies:

```
Package anahkiasen/underscore-php is abandoned, you should avoid using it. No replacement was suggested.
Package patchwork/utf8 is abandoned, you should avoid using it. Use symfony/polyfill-mbstring or symfony/string instead.
```

## Description

Determine how best to upgrade and clean our project dependencies.

**Comment by hugosolar** [comment]
Is that a Queulat dependency? if it is I'd say changing Queulat is urgent 😮
