### ISSUE TITLE
Queulat does not seem to install

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#85]
## Description

Our `composer.json` contains a requirement for `felipelavinz/queulat`. 

https://github.com/creativecommons/creativecommons-base/blob/1ca33ae3525fa7d789148e1030dd69ecfaaf5d0e/composer.json#L23-L25

Under the `repositories` section, we have configured a fork of the `queulat` package.

https://github.com/creativecommons/creativecommons-base/blob/1ca33ae3525fa7d789148e1030dd69ecfaaf5d0e/composer.json#L12-L17

For some reason, the `queulat` dependency does not seem to be installing, since the `felipelavinz` directory is empty after running `composer install`, despite the message indicating the archive was extracting:

```
- Installing felipelavinz/queulat (v2019.4.2): Extracting archive
```

## Reproduction

1. run `composer install`
2. observe the message "- Installing felipelavinz/queulat (v2019.4.2): Extracting archive"
3. look in the `felipelavinz/`directory
4. observe there are no files
5. look for a `creativecommons/queulat/` directory (from VCS)
6. observe that the `creativecommons/queulat` project does not seem to have been cloned

## Expectation

The `queulat` dependency would install correctly either from

- `felipelavinz/queulat` or
- `creativecommons/queulat`

## Additional context

Regardless of whether we decide to deprecate Queulat (#69) it would be useful if the dependency would install correctly.

**Comment by brylie** [comment]
@hugosolar does the `composer.json` file seem to be configured correctly from your perspective?

**Comment by hugosolar** [comment]
@brylie as far as I remember, we make a fork of Queulat since the original repo does not have a release yet, that's why `creativecommons/queulat` should be the repo to use on composer. I don't remember having any particular issues by installing `creativecommon-base` I can take a look in a minute

**Comment by brylie** [comment]
OK, thanks @hugosolar 

For context, I'm using our [Docker-based development environment](https://github.com/creativecommons/creativecommons-base/tree/main/development to run WordPress with the `creativecommons-base` theme. There is a line in the `docker-compose.yml` that creates a volume to link the repository root with the `wp-content/themes/creativecommons-base/` directory inside the image. 

https://github.com/creativecommons/creativecommons-base/blob/1ca33ae3525fa7d789148e1030dd69ecfaaf5d0e/development/docker-compose.yml#L13

The Docker volume would preserve the file structure, including the `vendor/`directory as a sub-directory of `wp-content/themes/creativecommons-base`. Is that where `vendor/` is expected to be found?

**Comment by hugosolar** [comment]
yes, and then you need to use that path to `vendor/autoload.php` on `mu-plugin/Queulat.php` 
take a look at this : https://github.com/felipelavinz/queulat#loading-queulat-as-mu-plugin
