### ISSUE TITLE
RFC: Use Gutenberg editor instead of custom post templates

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#95]
## Problem

This project currently defines come custom post behavior for video and gallery posts. In order to define some of the custom post functionality, we use the Queulat project, which we have agreed to deprecate (#69). The project roadmap has now shifted to focus on replacing functionality built with Queulat.

## Description

Rather than re-create a custom-code solution for video and gallery posts, we should use the [WordPress Gutenberg editor](https://wordpress.org/gutenberg/). The Gutenberg editor essentially allows content editors to create arbitrary post types, including video embeds and photo galleries.

There would be several benefits of using Gutenberg
- improved user experience based on thousands of WordPress installations and many releases
- flexibility for editors to define their own content types and layout (i.e. mobile-responsive rows and columns)
- little or no custom code required
- simplify our project dependencies
- Gutenberg is maintained by WordPress core developers and community contributors

## Alternatives

One alternative would be to continue to define custom post types. Defining our own custom post types means we need to maintain unnecessary code. It also limits the creative possibilities of content managers.

## Additional context

Gutenberg editor was released in 2018 with WordPress 5.0.

**Comment by annatuma** [comment]
In general, I like this idea, but we need to work with Comms to ensure design consistency with posts, whether they are pre-templated or created using Gutenberg. At its simplest, this could take the form of dummy, unpublished posts that content editors can copy, so that they are, essentially, a template for them to fill in the blanks of.

Let's also keep this in mind when it comes to creating page types/templates.

**Comment by brylie** [comment]
> t its simplest, this could take the form of dummy, unpublished posts that content editors can copy so that they are, essentially, a template for them to fill in the blanks of.

@annatuma, good suggestion. It sounds like [Gutenberg block templates](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-templates/) might serve the purpose you describe.

**Comment by brylie** [comment]
@annatuma, for the next iteration, I propose we test out the Gutenberg editor. We would work to ensure that Gutenberg rendered output follows the spirit of the Figma designs. Only if absolutely needed would we add any custom code, such as the Gutenberg block templates. :smiley: 

We may have started down the current development path by a) taking the design ideas as literal (waterfall-style) outcomes and b) directly or indirectly choosing to use the WordPress "classic" editor instead of Gutenberg. 

Design and development have somewhat equal influence on the process of bringing ideas into reality -- neither has the "final say." Instead, each participates in more of a conversation. As with any discussion, both participants lack some context while bringing together complementary parts of the picture. 

For example, it would be tedious to produce Figma sketches for myriad combinations of screen configuration, content, and accessibility considerations for each design idea. Similarly, we wouldn't want to code a custom template for every permutation of block content allowed by the Gutenberg editor.

This proposal was written with the intention of

- avoiding writing and maintaining custom code
- removing third-party dependencies
- working on what is unique to this project: the CSS styles
- aligning this project with WordPress core development

I believe this move would bring us closer to our goal of launching the revitalized theme on CreativeCommons.org.
