### ISSUE TITLE
Cleanup `/docs` folder after switching to GitHub pages

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#96]
## Problem

We recently switched to using GitHub pages for hosting static documentation for this project. Now that GitHub pages is enabled, there are a few minor housekeeping and bug fixing tasks.

## Description

We want to preserve all content from the previous Gridsome project while removing any Gridsome-specific boilerplate/configuration.

- [x] configure project to use [Just the Docs](https://pmarsceill.github.io/just-the-docs/#getting-started) remote theme
- [x] move [index page content](https://github.com/creativecommons/creativecommons-base/blob/main/docs/src/pages/Index.vue) to [`/docs/README.md`](https://github.com/creativecommons/creativecommons-base/blob/main/docs/README.md)
- [x] move all content to `/docs/` root directory
    - [x] [`/docs/content/*`](https://github.com/creativecommons/creativecommons-base/tree/main/docs/content) -> `/docs/`
- [x] double-check markdown content renders correctly (e.g. there may be some broken code blocks or other unneeded texts)
- [x] Make sure all content is available via a [navigation menu](https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/)
    - [x] double-check menu structure from [`docs/data/settings.json`](https://github.com/creativecommons/creativecommons-base/blob/main/docs/data/settings.json)
    - [x] add an [auxiliary nagivation link](https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/#auxiliary-links) to "[CC Open Source](https://opensource.creativecommons.org/)"
- [x] preserve structure of `/assets/**` folder while removing any unused elements
- [x] add the logo to the main template (`/assets/img/CC-theme-base.svg`) via a [theme configuration variable](https://pmarsceill.github.io/just-the-docs/docs/configuration/#site-logo)
- [x] Remove all Gridsome / unused code from at least the following locations
    - [x] `/docs/.editorconfig`
    - [x] `/docs/.eslintrc.js`
    - [x] `/docs/.gitignore`
    - [x] `/docs/.prettierrc.js`
    - [x] `/docs/gridsome.config.js`
    - [x] `/docs/gridsome.server.js`
    - [x] `/docs/netlify.toml`
    - [x] `/docs/package.json`
    - [x] `/docs/data/` directory
    - [x] remove empty `/docs/content/` directory (after moving content markdown files)
    - [x] remove `/docs/src/` directory after moving content from `/docs/src/pages/index.vue` to `/docs/README.md`
- [ ] Configure Repository Details: Website with new URL

## Additional context

Netlify and Gridsome add unnecessary complexity to this relatively simple static documentation site. The main idea here is to remove unnecessary complexity while preserving the essential content and functionality of the `creativecommons-base` documentation site.

**Comment by brylie** [comment]
@alainseys I've added this issue based on your work in issue #94. What else would you recommend including in the cleanup checklist?

**Comment by Prathan1Phumsri** [comment]
> ## ปัญหา
> เราเพิ่งเปลี่ยนไปใช้หน้า GitHub เพื่อโฮสต์เอกสารแบบคงที่สำหรับโครงการนี้ เมื่อเปิดใช้งานหน้า GitHub แล้ว มีงานดูแลทำความสะอาดและแก้ไขข้อผิดพลาดเล็กน้อย
> 
> ## คำอธิบาย
> เราต้องการรักษาเนื้อหาทั้งหมดจากโครงการ Gridsome ก่อนหน้าในขณะที่ลบต้นแบบ/การกำหนดค่าเฉพาะ Gridsome ใดๆ
> 
> * [x] กำหนดค่าโครงการเพื่อใช้ธีมระยะไกล[Just the Docs](https://pmarsceill.github.io/just-the-docs/#getting-started)
> * [x] ย้าย[เนื้อหาของหน้าดัชนี](https://github.com/creativecommons/creativecommons-base/blob/main/docs/src/pages/Index.vue)ไปที่[`/docs/README.md`](https://github.com/creativecommons/creativecommons-base/blob/main/docs/README.md)
> * [x] ย้ายเนื้อหาทั้งหมดไปยัง`/docs/`ไดเรกทอรีราก
>   
>   * [x]  [`/docs/content/*`](https://github.com/creativecommons/creativecommons-base/tree/main/docs/content) -> `/docs/`
> * [x]  ตรวจสอบเนื้อหา markdown ซ้ำอีกครั้งว่าแสดงผลอย่างถูกต้อง (เช่น อาจมีบล็อกโค้ดที่ใช้งานไม่ได้หรือข้อความที่ไม่จำเป็นอื่นๆ)
> * [x] ตรวจสอบให้แน่ใจว่าเนื้อหาทั้งหมดพร้อมใช้งานผ่าน[เมนูนำทาง](https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/)
>   
>   * [x]  ตรวจสอบโครงสร้างเมนูซ้ำจาก [`docs/data/settings.json`](https://github.com/creativecommons/creativecommons-base/blob/main/docs/data/settings.json)
>   * [x] เพิ่ม[ลิงค์การนำทางเสริม](https://pmarsceill.github.io/just-the-docs/docs/navigation-structure/#auxiliary-links)ไปที่ " [CC Open Source](https://opensource.creativecommons.org/) "
> * [x] รักษาโครงสร้างของ`/assets/**`โฟลเดอร์ในขณะที่ลบองค์ประกอบที่ไม่ได้ใช้ออก
> * [x]  add the logo to the main template (`/assets/img/CC-theme-base.svg`) via a [theme configuration variable](https://pmarsceill.github.io/just-the-docs/docs/configuration/#site-logo)
> * [x]  Remove all Gridsome / unused code from at least the following locations
>   
>   * [x]  `/docs/.editorconfig`
>   * [x]  `/docs/.eslintrc.js`
>   * [x]  `/docs/.gitignore`
>   * [x]  `/docs/.prettierrc.js`
>   * [x]  `/docs/gridsome.config.js`
>   * [x]  `/docs/gridsome.server.js`
>   * [x]  `/docs/netlify.toml`
>   * [x]  `/docs/package.json`
>   * [x]  `/docs/data/` directory
>   * [x]  remove empty `/docs/content/` directory (after moving content markdown files)
>   * [x]  remove `/docs/src/` directory after moving content from `/docs/src/pages/index.vue` to `/docs/README.md`
> * [ ]  Configure Repository Details: Website with new URL
> 
> ## Additional context
> Netlify and Gridsome add unnecessary complexity to this relatively simple static documentation site. The main idea here is to remove unnecessary complexity while preserving the essential content and functionality of the `creativecommons-base` documentation site.
