### ISSUE TITLE
Use GitHub actions to test changes in Docker images

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#97]
Split from #93

@alainseys made the excellent recommendation that we use GitHub actions to test our Docker images. GitHub actions can be triggered by pull requests and can be used as part of the approval process.

We have 2000 minutes a month on the free plan, with additional minutes billed as described on the [GitHub billing page](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions).

**Comment by alainseys** [comment]
@brylie  if you have a github worker running on a vm on a cloud machine you also have some additional minutes extra you can easy setup this on digital ocean or even on a tradional hoster like hetzner , if interested i can setup this.(github actions and or the worker)

**Comment by alainseys** [comment]
Hy @brylie  i have done this in the following  pr #98 this is extenable to even pull request now i have created this on git push trigger.

**Comment by kgodey** [comment]
GitHub Actions is actually free for public repositories; there's no 2000 minute limit.
